name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: tom783/tom783@master
        with:
          WAKATIME_API_KEY: 6b44d58b-ec69-4708-b4ac-66942e4d5551
          GH_TOKEN: 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
          SHOW_TOTAL_CODE_TIME: True
          SHOW_COMMIT: True
          SHOW_DAYS_OF_WEEK: True
